services:
  - type: web
    name: proyecto-riesgo-crediticio
    env: python
    plan: free
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r backend/requirements.txt
      cd frontend && npm install && npm run build

    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: "10000"
      - key: ML_MODEL_PATH
        value: "backend/app/ml_engine/ml_model.joblib"
      - key: MONGO_URI
        value: "mongodb+srv://heinsperr_db_user:8qafy5hjTJ1ZuzIN@aplazadossi.y1wl5at.mongodb.net/RiesgoCrediticio?retryWrites=true&w=majority"
